name: flutter_recipes
description: "A Flutter recipe app."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.9.0
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  google_nav_bar: ^5.0.6
  provider: ^6.1.2
  flutter_slidable: ^3.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - images/

  uses-material-design: true
